name: Build
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm install
    - name: return
      run: cd ../../
    - name: build
      run: npx electron-builder build --win -p always
