name: Build
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm install
    - name: return
      run: cd ../../
    - name: build
      run: npx electron-builder build --win -p always
    - name: ls 
      run: ls ./dist
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: <v1.0.1>
        release_name: <v1.0.1>
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/anti-afk-for-games Setup 1.0.0.exe
        asset_name: anti-afk-for-games-Setup-1.0.0.exe
        asset_content_type: application/exe

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
