name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm i
    - name: return
      run: cd ../../
    - name: build
      run: npx electron-builder --linux --win --publish always index.js
    - name: publish
      run: npm run publish
